# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-00402f6f-cb77-4aa8-951a-1458bf416e6d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-00402f6f-cb77-4aa8-951a-1458bf416e6d".device = "/dev/disk/by-uuid/00402f6f-cb77-4aa8-951a-1458bf416e6d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B82B-8011";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-70721ac2-f0e1-4eba-a1d5-c6942397331c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
